version: 2
project_name: json-stats-exporter

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - formats: binary
checksum:
  disable: true
snapshot:
  version_template: "{{ .Tag }}"
